apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: s0xkald4a-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:6e58c4c0b8f7f0389add8eaa52bfb3662e7abca2@sha256:126946dd9662622a81cfa29824275f4787098ea5e2a49584b6edc5d04b2ada5b
          name: container-image
